### ISSUE TITLE
"New!" indicator appears on top of vote comment balloon

### ISSUE THREAD

**Issue by ldjb** [colons/nkd.su#122]
![new_over](https://cloud.githubusercontent.com/assets/2071756/6428244/81cf56ca-bf92-11e4-9e18-09cd271fbeb3.png)
This could be fixed by making [`.deets`'s `z-index`](https://github.com/colons/nkd.su/blob/master/nkdsu/static/less/_track.less#L138) >= to [`.track.new::before`'s `z-index`](https://github.com/colons/nkd.su/blob/master/nkdsu/static/less/_track.less#L250), though I'm not sure whether that would have any unintended side-effects.

**Comment by Tomo-san** [comment]
Thanks for this, that merge should fix that issue.
