### ISSUE TITLE
Highlight user icons if they are new to the site (first show/month/etc)

### ISSUE THREAD

**Issue by theshillito** [colons/nkd.su#128]
I would like to encourage repeat visits by playing tracks for new accounts voting for the first time. Could do with a way of seeing it easily without remembering who has which icon/username.

**Comment by theshillito** [comment]
This ties in with https://github.com/colons/nkd.su/issues/127 I guess

**Comment by colons** [comment]
okay so i've been considering replacing the highlighted border that appears around twoots with something like a lil' [speech bubble](http://fontawesome.io/icon/commenting/) or something in the bottom right for a while, cuz it's way more explicit and obvious that way, and i think these would also fit very well in this place, thoughts?

**Comment by theshillito** [comment]
Yeah, that would be cool. I've also thought about a larger admin view on a per-track basis? Like a track expands out so I can see everything in one go while talking rather than having to move mouse about to view comments, etc. Something like this image right here oh the wonders of technology:
![expanded admin view](https://cloud.githubusercontent.com/assets/1828418/15511401/3bb1002c-21d3-11e6-8bad-cb545abd6666.png)

**Comment by theshillito** [comment]
Can we change this to whether a user has had a song played or not on any week, as there has been at least once where a new user voted for a song shortly before the end of the show as that's when it was trending, and I *think* they were not tagged as new on the following week.
