### ISSUE TITLE
we're gonna need to do something to let people not have votes appear on their public timeline

### ISSUE THREAD

**Issue by colons** [colons/nkd.su#130]
we have to account for [this nonsense](https://blog.twitter.com/express-even-more-in-140-characters)

perhaps one nkdsu tweet that all votes are in response to? not enforced, natch, but at least the default that happens when you use the native vote butans

**Comment by homsar** [comment]
Does 1ed2078 not fix this? Or is a more elegant solution desirable? (Fresh twoots for each show?)
