### ISSUE TITLE
Flatten accents when searching

### ISSUE THREAD

**Issue by theshillito** [colons/nkd.su#149]
e.g. a search for "Marchen Madchen" should return songs tagged with "Märchen Mädchen"

Combined with #148 it should make searching much more reliable, and it means we don't need to add a tag for every use of accents and stuff (which there's a few, see also songs by "fhána" tagged currently as "fhana").

**Comment by homsar** [comment]
[This is built into django 1.8 onwards](https://docs.djangoproject.com/en/dev/ref/contrib/postgres/lookups/#std:fieldlookup-unaccent), so probably makes sense to defer this until the current master branch goes into production?

**Comment by theshillito** [comment]
On a similar note to this, might be a good idea to elongate and/or flatten macrons if searched with, following this discussion https://twitter.com/NekoDesuRadio/status/1139978880570265600

It will mean storing track metadata with macrons and then allowing people to search with or without I think. Alternatively, I could just use tags with #148 but there's quite a few artists, titles and anime that would use macrons...
