### ISSUE TITLE
.hack anime pages break

### ISSUE THREAD

**Issue by homsar** [colons/nkd.su#158]
[This page](https://nkd.su/search/?q=.hack) links to various .hack anime, all of which 404. Fate anime work, so presumably it's the dot at the start that breaks it.

See e.g. [Legend of the Twilight Bracelet](https://nkd.su/new-world/2425A3B830F1188A/)

**Comment by colons** [comment]
See also: https://nkd.su/katte-ni-my-soul/DDF4C32FE97946B1/

**Comment by colons** [comment]
Fixed this by dropping `mod_wsgi` in favour of running the site under gunicorn and proxying to that.
