### ISSUE TITLE
Tally how many songs have been played on the artist pages

### ISSUE THREAD

**Issue by euricaeris** [colons/nkd.su#167]
So for example, on Mia REGINA's page: https://nkd.su/artist/Mia%20REGINA/ 

You'd have an '8/10 tracks played' at the top, under the band name. I've noticed a lot of people voting for the same artists, and it'd be kinda neat to give people a bit of a goal to aim for (as well as a way to tell at a glance if there are songs that haven't been played yet).

Perhaps if it's not too tricky to figure out, a running count for total song plays could also go up there.

**Comment by colons** [comment]
Artist pages are currently pretty cheap and quick to draw right now, so adding this shouldn't be an undue load?
