### ISSUE TITLE
Having a page for 'add this song to the library' requests

### ISSUE THREAD

**Issue by euricaeris** [colons/nkd.su#92]
My thinking on this is that there could be a page of song requests that have been submitted, and people can vote on them in the same way as they would for the main show. The point of the votes is to show @theshillito what songs people are desperate for. When/if the song is added/played, the votes may even carry over to the main show. 

There would need to be a behind the scenes 'send to page' and 'trash' option, just to prevent duplicates and spam. This could be a good way to get a popular OP on the show that you may not have heard of, before that obscure ED that only one person cares about.

EDIT: You could even force songs to vanish from this list every 2 weeks to prevent it from becoming bogged down.

EDIT2: Also a good way of getting return visitors.

**Comment by theshillito** [comment]
Should this be marked as closed? There's the view the elves see now, although it's not a public-facing thing for people to vote on (and that is kinda replaced by Patreon anyway)

**Comment by theshillito** [comment]
Metadata listing still needs a few fixes on #153 but the request listing is done.
