### ISSUE TITLE
Tracks pretty much all look the same

### ISSUE THREAD

**Issue by colons** [colons/nkd.su#99]
Proposed solution: put subtle, blurry, low-quality JPEG art in the background of every track we can find track or album or artist art for on last.fm. [colons.co] is a useful case study in how big you can blow up a really tiny jpeg and have it still be pretty if it's blurred just right, and those aren't even opaque like these would probably have to be, so this could be made with reasonably insignificant bandwidth impact.

[colons.co]: http://colons.co/

**Comment by theshillito** [comment]
Is this issue now addressed by the background artwork?
